import test from 'node:test';import assert from 'node:assert/strict';import {createHash,generateKeyPairSync,sign} from 'node:crypto';import {processCampaign,checkedNewsletter} from './cockpit-dispatch.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex'),id='6ee38b68-940e-4ede-815c-64a1ec7b75c2',contentHash=hash('conteúdo'),html=`<!-- ABREV_COCKPIT:${id}:${contentHash} -->`,p={version:1,purpose:'newsletter',repository:'Abrev-IA/abrev-site',publicationId:id,contentHash,htmlHash:hash(html),campaignId:id+'-'+contentHash,slug:'estudo',url:'https://abrev.org/blog/estudo.html',requestedAt:'2026-10-08T20:00:00Z'};
function fixture(){const files=new Map(),calls=[];return {files,calls,adapters:{read:async path=>files.get(path),write:async(path,obj)=>{assert.ok(!files.has(path));files.set(path,obj);calls.push(path.includes('/claims/')?'claim':'receipt')},article:async()=>html,diagnostic:async()=>({ok:true,cota_restante:90}),broadcast:async()=>{calls.push('send');return {ok:true,broadcast:{ativos:7,enviados:7,sem_cota:0,cota_restante:83}}},workflowRunId:'123'}};}
test('Newsletter aceita somente solicitação assinada com destino e campanha vinculados',()=>{const keys=generateKeyPairSync('ed25519'),envelope=x=>{const data=JSON.stringify(x);return {data,signature:sign(null,Buffer.from(data),keys.privateKey).toString('base64')}};assert.equal(checkedNewsletter(envelope(p),keys.publicKey).campaignId,p.campaignId);assert.throws(()=>checkedNewsletter(envelope({...p,url:'https://evil.test'}),keys.publicKey));assert.throws(()=>checkedNewsletter({...envelope(p),data:'{}'},keys.publicKey));});
test('Registro antecede disparo e comprovante impede segundo envio',async()=>{const f=fixture(),r=await processCampaign(p,f.adapters);assert.equal(r.sent,7);assert.equal(r.state,'ENVIADA');assert.deepEqual(f.calls,['claim','send','receipt']);await processCampaign(p,f.adapters);assert.deepEqual(f.calls,['claim','send','receipt']);});
test('Timeout após disparo fica incerto e nunca é repetido automaticamente',async()=>{const f=fixture();f.adapters.broadcast=async()=>{f.calls.push('send');throw Error('timeout')};assert.equal((await processCampaign(p,f.adapters)).state,'INCERTO');await processCampaign(p,f.adapters);assert.equal(f.calls.filter(c=>c==='send').length,1)});
test('Registro existente sem recibo impede envio e preserva dúvida',async()=>{const f=fixture();f.files.set('automation/newsletter/claims/'+p.campaignId+'.json',p);assert.equal((await processCampaign(p,f.adapters)).state,'INCERTO');assert.ok(!f.calls.includes('send'))});
test('Versão pública diferente bloqueia antes de disparar',async()=>{const f=fixture();f.adapters.article=async()=>'alterado';assert.equal((await processCampaign(p,f.adapters)).state,'BLOQUEADA');assert.ok(!f.calls.includes('send'))});
test('Cota parcial registra quantidade real sem reenvio',async()=>{const f=fixture();f.adapters.broadcast=async()=>({ok:true,broadcast:{ativos:7,enviados:5,sem_cota:2,cota_restante:0}});const r=await processCampaign(p,f.adapters);assert.equal(r.state,'PARCIAL');assert.equal(r.sent,5)});
